### ISSUE TITLE
Kafka connect only pull servicenow table records during and only in  first initialization

### ISSUE THREAD

**Issue by sookeke** [IBM/kafka-connect-servicenow#7]
Hello,

I trying capturing changes in service now application table using this kafka-connect-servicenow plugin but I realized that the only time a record is being captured is during the first kafka connector initialization stage. After that, any new record insert into the servicenow table are not being captured, including updates are not being capture.

Is this plugin supposed to capture continuously new record  and change events for the target table and into the kafka topic? or I'm I doing something wrong here?

Here is my kafka connector config and any help will be appreciated. Thank you

kind: KafkaConnector
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: servicenow-connector
  labels:
    strimzi.io/cluster: jpidp-cluster
  namespace: 5b7aa5-test
spec:
  class: com.ibm.ingestion.connect.servicenow.ServiceNowSourceConnector
  tasksMax: 1
  config:
    servicenow.client.base.uri: https://dev141657.service-now.com
	servicenow.client.oauth.clientid: ****
	servicenow.client.oauth.clientsecret: ****
	servicenow.client.oauth.username: **
	servicenow.client.oauth.userpassword: ******
	table.whitelist: x_939755_ops_openshift_user_access
	table.whitelist.x_939755_ops_openshift_user_access.name: x_939755_ops_openshift_user_access
	table.whitelist.x_939755_ops_openshift_user_access.timestamp.field.name: sys_updated_on
	table.whitelist.x_939755_ops_openshift_user_access.identifier.field.name: sys_id
	table.whitelist.x_99755_ops_openshift_user_access.partition.type: default
	topic.prefix: ocp.access
	timestamp.initial.query.hours.ago: 720

@mmillies @stevemar

**Comment by sookeke** [comment]
@mike-treadway @stevemar

**Comment by mvitor** [comment]
Hi Stanley,

Have you been able to check if the server time zone and the Servicenow user
time zone match?

I hope that helps.

Thanks & Regards,
Marcio

**Comment by sookeke** [comment]
@mvitor Thank you very much I realize the server time zone and ServiceNow time zone are different. I was able to capture the change event using this plugin. Thank you

**Comment by VagnerBelfort** [comment]
hey guys how are you?

What would these fields be in service now?
servicenow.client.oauth.clientid: ****
servicenow.client.oauth.clientsecret: ****

I'm trying to put the same username and password as these:
servicenow. cliente.oauth.username: **
servicenow.client.oauth.userpassword: ******

but I'm getting access_denied error.

In logstastash I just configured this:

input {
    http_poller {
        urls => {
            servicenow => {
                method => get
                url => "https://dev.service-now.com/api/now/table/incident?sysparm_limit=1"
                headers => { Accept => "application/json" }
                user => "*****"
                password => "****"
            }
        }
        request_timeout => 1
        schedule => { every => "1s" }
        codec => "json"
    }
}

output {
    elasticsearch {
        hosts => ["http://xxx.xxx.xxx:9200", "http://xxx.xxx.xxx:9200", "http://xxx.xxx.xxx:9200"]
        index => "dev-itsm-%{+YYYY.MM.dd}"
    }
    kafka {
        topic_id => "XXXXXXX"
        reconnect_backoff_ms => 20000
        bootstrap_servers => "xxx.xxx.xxx:6667, xxx.xxx.xxx:6667, xxx.xxx.xxx:6667"
        jaas_path => "/etc/logstash/jaas/jaas.conf"
        kerberos_config => "/etc/krb5.conf"
        sasl_kerberos_service_name => "kafka"
        security_protocol => "SASL_PLAINTEXT"
        sasl_mechanism => "GSSAPI"
        #codec => plain { charset => "UTF-8" }
        codec => json { charset => "UTF-8" }
    }

can you help me?
